From alexpacheco/centos7:desktop

Label "maintainer"="alp514@lehigh.edu" \
      "os"="CentOS 7" \
      "compiler"="GCC 4.8.5" \
      "app"="Desktop" \
      "description"="MATE Desktop  for LURC's OOD" 

# Install MATE desktop
RUN yum -y groupinstall "MATE Desktop" \
 && yum -y install xorg-x11-apps xorg-x11-xauth mesa-dri-drivers \
 && rm -rf /var/cache/yum \
 && yum clean all

