From alexpacheco/leap:15.2-desktop

Label "maintainer"="alp514@lehigh.edu" \
      "os"="Leap 15.2" \
      "compiler"="GCC 7.5.0" \
      "app"="Desktop" \
      "description"="Leap 15.2 XFCE Desktop for LURC's OOD"

# Install XFCE desktop
RUN zypper update -y \
 && zypper in -y patterns-xfce-xfce xfce4-terminal


